### ISSUE TITLE
Uncaught Error: Unexpected endLine: 8Column: 0Char: 

### ISSUE THREAD

**Issue by ratheos** [AtomLinter/linter-xmllint#86] opened 2017-11-15 13:26 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.0 x64
**Electron**: 1.6.15
**OS**: Unknown Windows version
**Thrown From**: [linter-xmllint](https://github.com/AtomLinter/linter-xmllint) package 1.4.3

### Stack Trace

Uncaught Error: Unexpected end
Line: 8
Column: 0
Char: 

```
At events.js:160

Error: Unexpected end
Line: 8
Column: 0
Char: 
    at error (/packages/linter-xmllint/node_modules/sax/lib/sax.js:651:10)
    at end (/packages/linter-xmllint/node_modules/sax/lib/sax.js:662:7)
    at SAXParser.end (/packages/linter-xmllint/node_modules/sax/lib/sax.js:154:24)
    at SAXStream.end (/packages/linter-xmllint/node_modules/sax/lib/sax.js:248:18)
    at ReadableString.onend (_stream_readable.js:511:10)
    at Object.onceWrapper (events.js:290:19)
    at emitNone (events.js:86:13)
    at ReadableString.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
undefined -8:50.6.0 intentions:highlight (input.hidden-input)
     -8:45.4.0 core:copy (input.hidden-input)
     -8:43.5.0 editor:newline (input.hidden-input)
     -8:43.3.0 intentions:highlight (input.hidden-input)
     -8:43.2.0 core:paste (input.hidden-input)
     -8:40.1.0 core:backspace (input.hidden-input)
     -8:29.9.0 intentions:highlight (input.hidden-input)
     -8:29.6.0 core:save (input.hidden-input)
     -4:58.2.0 core:backspace (input.hidden-input)
     -4:57.3.0 core:move-left (input.hidden-input)
     -4:56.3.0 core:backspace (input.hidden-input)
     -4:56.1.0 core:move-left (input.hidden-input)
  2x -4:55.7.0 core:backspace (input.hidden-input)
     -0:51.4.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -0:51.4.0 editor:newline (input.hidden-input)
 14x -0:49.9.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.6 
busy-signal 1.4.3 
emmet 2.4.3 
intentions 1.1.5 
linter 2.0.0 
linter-ui-default 1.6.10 
linter-xmllint 1.4.3 
xml-formatter 0.11.0 
```

**Comment by dirk-thomas** [comment] 2017-12-03 17:15
Duplicate of #85. Please comment there with the necessary information how to reproduce the problem.

**Closed by dirk-thomas** 2017-12-03 17:15 UTC
