### ISSUE TITLE
Linter not applied if xml file not saved on disk

### ISSUE THREAD

**Issue by gliviu** [AtomLinter/linter-xmllint#68] opened 2016-09-07 07:44 UTC
Steps:
* Create new file (File->New file)
* Paste some xml
* Manually change grammar to xml (ctrl-shift-L)
* Change the xml so that it becomes invalid
* Observe the linter has nothing to complain
* Save the file on disk
* Linter detects the error

Versions: Atom 1.10.0/Windows 7

On the other hand, if the file is already persisted on disk and I do some changes without saving them, the linter works fine. So it seems it is able to work on content that is only in memory.

**Comment by dirk-thomas** [comment] 2016-09-07 14:16
Thank you for the report. I can reproduce the problem. But it seems like this linter is not even being triggered. I have the same problem with other on-the-fly linters (e.g. pyflakes).

@steelbrain Do you see the same behavior and agree that it should run the linter in this case? Could it be that steelbrain/linter#1052 is responsible for this?

**Comment by steelbrain** [comment] 2016-09-07 14:59
@dirk-thomas It's unrelated to the bug you referenced but is still a behavior of the base linter. Linter by design ignores any files that are not saved on disk, the reason for it is that almost all of the linters lint file paths and unsaved ones have no file paths

**Comment by dirk-thomas** [comment] 2016-09-07 15:00
Can it be enabled for linters which support on-the-fly?

**Comment by steelbrain** [comment] 2016-09-07 15:03
I am personally against even that, and the reasons might convince even you too. ESLint for example is a on-the-fly linter, it still needs the file path to resolve the presets and configs of the contents

**Comment by dirk-thomas** [comment] 2016-09-07 15:05
I agree that some linters might not be able to handle that case. But it would still be nice if the linter which can handle it get the opportunity. A linter which doesn't can easily skip editors without a path but linters which want to be triggered can't do so on their own.

**Comment by steelbrain** [comment] 2016-09-07 15:06
The trouble might not be worth it, how often do we want to see errors in files that we haven't even saved yet?
I have been developing for years and I always create a file first, fill it later so linters work on it. Perhaps the users could adopt this course of action.

**Comment by dirk-thomas** [comment] 2016-09-07 15:10
It might not be your workflow but it seems that several users have run into a similar situation and I agree with them that the current behavior is not what I would expect to happen. It is basically a silent failure since you expect the linting to happen after choosing the right syntax for the current "file".

**Comment by steelbrain** [comment] 2016-09-07 15:12
Even if I do remove this check in the base linter, it will break those tons of linters out there, because we have no way of knowing if they check if file path exists (which they don't because they are sure linter only triggers them when it does)

**Comment by dirk-thomas** [comment] 2016-09-07 15:14
That sounds like such a change should go into a new major version and a note in the changelog should let linter developers know about the change and how they should handle this specific case.

**Comment by steelbrain** [comment] 2016-09-07 15:17
We are on the edge of releasing linter@2.x, if you can open this issue in the base linter repo and gather some votes, I'd be happy to implement it :) (even though I'm personally against it 😛 )

**Comment by dirk-thomas** [comment] 2016-09-07 15:24
Sounds good. I created steelbrain/linter#1235 and will close this since this linter can't address the requested feature.

**Closed by dirk-thomas** 2016-09-07 15:24 UTC
Labels: bug
