### ISSUE TITLE
Uncaught Error: Attribute without valueLine: 2 Column: 16 Char:>

### ISSUE THREAD

**Issue by TheHaricover** [AtomLinter/linter-xmllint#91] opened 2018-03-13 15:12 UTC
Steps : 1) Open an XML file
           2) Delete a line, for example : ```<peoples>
      <people>Somebody</people>
    </peoples>```

**Atom**: 1.24.1 x64
**Electron**: 1.6.16
**OS**: Windows 10 Familial (Version 10.0.16299 Number 16299)
**Thrown From**: [linter-xmllint](https://github.com/AtomLinter/linter-xmllint) package 1.4.3

### Stack Trace

Uncaught Error: Attribute without value
Line: 2
Column: 16
Char: >

```
At events.js:160

Error: Attribute without value
Line: 2
Column: 16
Char: >
    at error (/packages/linter-xmllint/node_modules/sax/lib/sax.js:651:10)
    at strictFail (/packages/linter-xmllint/node_modules/sax/lib/sax.js:677:7)
    at SAXParser.write (/packages/linter-xmllint/node_modules/sax/lib/sax.js:1321:13)
    at SAXStream.write (/packages/linter-xmllint/node_modules/sax/lib/sax.js:239:18)
    at ReadableString.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at ReadableString.emit (events.js:188:7)
    at ReadableString.Readable.read (_stream_readable.js:381:10)
    at flow (_stream_readable.js:761:34)
    at resume_ (_stream_readable.js:743:3)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
  2x -7:44.6.0 core:copy (input.hidden-input)
     -7:42.3.0 editor:newline (input.hidden-input)
     -7:41.8.0 core:move-up (input.hidden-input)
     -7:41.6.0 intentions:highlight (input.hidden-input)
     -7:41.5.0 core:paste (input.hidden-input)
     -7:41.2.0 intentions:highlight (input.hidden-input)
     -7:41.1.0 core:save (input.hidden-input)
     -7:37.6.0 editor:newline (input.hidden-input)
     -7:37.3.0 core:move-up (input.hidden-input)
     -7:37.1.0 intentions:highlight (input.hidden-input)
     -7:37 core:paste (input.hidden-input)
     -7:36.5.0 intentions:highlight (input.hidden-input)
     -7:36.4.0 core:save (input.hidden-input)
  2x -7:04.8.0 core:backspace (input.hidden-input)
     -7:04.4.0 intentions:highlight (input.hidden-input)
     -7:04.4.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.32.2 
atom-clock 0.1.16 
atom-ide-ui 0.9.3 
atom-python-run 0.9.6 
autocomplete-python 1.10.5 
autocomplete-xml 0.9.4 
autumn-highlighter-syntax 1.13.0 
busy-signal 1.4.3 
highlight-selected 0.13.1 
Hydrogen 2.3.0 
ide-csharp 0.6.2 
intentions 1.1.5 
kite 0.72.0 
linter 2.2.0 
linter-ui-default 1.7.1 
linter-xmllint 1.4.3 
package-switch 0.5.0 
python-tools 0.6.9 
sync-settings 0.8.5 
webbox-color 0.5.9 
xml-formatter 0.11.0 
```

**Comment by TheHaricover** [comment] 2018-03-13 15:20
Ok, I found out that this error seems to appear when I make a mistake.
I wrote ```<document name=Ring of patient/>``` and the package made this ```Error: Unquoted attribute value
Line: 4
Column: 22
Char: R
    at error (C:\Users\rochr\.atom\packages\linter-xmllint\node_modules\sax\lib\sax.js:651:10)
    at strictFail (C:\Users\rochr\.atom\packages\linter-xmllint\node_modules\sax\lib\sax.js:677:7)
    at SAXParser.write (C:\Users\rochr\.atom\packages\linter-xmllint\node_modules\sax\lib\sax.js:1367:13)
    at SAXStream.write (C:\Users\rochr\.atom\packages\linter-xmllint\node_modules\sax\lib\sax.js:239:18)
    at ReadableString.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at ReadableString.emit (events.js:188:7)
    at ReadableString.Readable.read (_stream_readable.js:381:10)
    at flow (_stream_readable.js:761:34)
    at resume_ (_stream_readable.js:743:3)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)```

**Comment by TheHaricover** [comment] 2018-03-13 15:22
Well, I squinted. That's not even the same mistake, my bad. I'll delete the previous post.

**Comment by dirk-thomas** [comment] 2018-03-22 04:01
Without the file in question I am not able to reproduce the problem. Hence I am closing this for now.

**Closed by dirk-thomas** 2018-03-22 04:01 UTC
