### ISSUE TITLE
Schema validation regex is also not working on windows

### ISSUE THREAD

**Issue by jgrodskiy-donlen** [AtomLinter/linter-xmllint#50] opened 2016-02-17 18:46 UTC
Hello,

Seems to be a similar issue .  Hopefully this is enough.

![image](https://cloud.githubusercontent.com/assets/17149683/13120649/5ed18352-d574-11e5-8e3c-dd53b85c1a00.png)

**Comment by dirk-thomas** [comment] 2016-02-17 19:01
Can you please also provide the exact output of the following command:

    xmllint --noout --schema test.xsd test.xml

In the debugging messages it looks like it doesn't contain the filename and line number in the beginning of each line.

**Comment by jgrodskiy-donlen** [comment] 2016-02-17 19:04
Here you go

![image](https://cloud.githubusercontent.com/assets/17149683/13121170/e260cc44-d576-11e5-8207-f5584ee20670.png)

**Comment by dirk-thomas** [comment] 2016-02-17 19:06
That is just bad :worried: It doesn't even mention where in the file the problem is. On Linux the output is:

    test.xml:3: element cat: Schemas validity error : Element 'cat': This element is not expected. Expected is ( animal ).
    test.xml fails to validate

Can you please check if `xmllint` has any options to get "more" output including the line number? Or if there is a newer version of `xmllint` which you can install?

**Comment by jgrodskiy-donlen** [comment] 2016-02-17 19:14
Good news, got it to work...

Bad news I downgraded versions and switched to x86 to do it.  For now just update the instructions to indicate to use this version for windows?.

![image](https://cloud.githubusercontent.com/assets/17149683/13121543/3dc2869e-d578-11e5-8f31-abe92ceb4525.png)

**Comment by dirk-thomas** [comment] 2016-02-17 19:38
It would be great if you could create a pull request to update the [README](https://github.com/AtomLinter/linter-xmllint/blob/master/README.md) file with instructions which work on Windows and add a note what doesn't work.

This should also be filled upstream against `xmllint` since it seems like a pretty bad regression on Windows.

**Comment by jgrodskiy-donlen** [comment] 2016-02-17 19:41
Will do, and I will follow up and see more about xmllint.

**Comment by dirk-thomas** [comment] 2016-02-25 05:52
Addressed by #51.

**Comment by dirk-thomas** [comment] 2016-02-25 05:53
Addressed by #51. Thank you for providing the PR.

**Closed by dirk-thomas** 2016-02-25 05:52 UTC
